In [1]:
import pandas as pd
import numpy as np
from paraplume.infer import predict_paratope, predict_paratope_seq

/home/athenes/.pyenv/versions/paraplume2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Go to the tutorial folder
!pwd

/home/athenes/Paraplume/tutorial

# Inference for a csv file

### Paired chain

In [3]:
test=pd.read_csv("./paired.csv")
paratope_test=predict_paratope(test)
paratope_test.head(5)

2025-12-25T21:04:46.199310Z [info     ] Loading training summary dictionary. path=/home/athenes/Paraplume/paraplume/trained_models/large/summary_dict.json

2025-12-25T21:04:46.245811Z [info     ] Loading model.                 path=/home/athenes/Paraplume/paraplume/trained_models/large/checkpoint.pt

100%|██████████| 1/1 [00:01<00:00,  1.53s/it]
100%|██████████| 1/1 [00:02<00:00,  2.70s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 148.32it/s]
100%|██████████| 1/1 [00:03<00:00,  3.38s/it]
100%|██████████| 1/1 [00:07<00:00,  7.02s/it]
100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
  0%|          | 0/1 [00:00<?, ?it/s]You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
100%|██████████| 1/1 [00:03<00:00,  3.98s/it]

,sequence_heavy,sequence_light,model_prediction_heavy,model_prediction_light
0,QAYLQQSGAELVKPGASVKMSCKASDYTFTNYNMHWIKQTPGQGLE...,EIVLTQSPTTMAASPGEKITITCSARSSISSNYLHWYQQKPGFSPK...,"[0.048334908, 0.010902395, 0.0038453373, 4.253...","[0.035070572, 0.050952498, 0.0011520551, 5.953..."
1,EFQLQQSGPELVKPGASVRMSCKASGYTFASYVMHWVRQNPGQGLE...,EIVLTQSPTTMAASPGEKITITCSASSSISSNYLHWYQQKPGFSPK...,"[0.08309175, 0.031532332, 0.00068060716, 6.667...","[0.02443566, 0.035579085, 0.0006735277, 3.1748..."
2,EFQLQQSGPELVKPGTSVKMSCKASGYTFSDYVLHWVKPKPGQGLE...,EIVLTQSPTTMAASPGEKITITCSANSSISSNYLHWYQQKPGFSPK...,"[0.08545888, 0.03271081, 0.0005217243, 6.06204...","[0.033916645, 0.03693516, 0.0007811487, 3.3286..."
3,EFQLQQSGPELVKPGASVKMSCKASGYTFSNYVLHWVKQRPGQGLE...,EIVLTQSPTTMAASPGEKITITCSANSSISSNYLHWYQQKPGFSPK...,"[0.06900511, 0.033255324, 0.0005228337, 6.8596...","[0.03797671, 0.034443863, 0.0008039044, 3.4990..."
4,EFQLQQSGPELVKPGASVKMSCKASGYTFTSYVIHWVKQKPGQGLE...,EIVLTQSPTTMAASPGEKITVTCSANSTISSNYFHWYQQKPGFSPK...,"[0.08857389, 0.049174782, 0.00067764096, 1.659...","[0.03787743, 0.036175456, 0.001057556, 6.58868..."

In [4]:
print("First heavy chain sequence",list(paratope_test["sequence_heavy"].values[0]))
print("Paratope predictions",paratope_test["model_prediction_heavy"].values[0])

First heavy chain sequence ['Q', 'A', 'Y', 'L', 'Q', 'Q', 'S', 'G', 'A', 'E', 'L', 'V', 'K', 'P', 'G', 'A', 'S', 'V', 'K', 'M', 'S', 'C', 'K', 'A', 'S', 'D', 'Y', 'T', 'F', 'T', 'N', 'Y', 'N', 'M', 'H', 'W', 'I', 'K', 'Q', 'T', 'P', 'G', 'Q', 'G', 'L', 'E', 'W', 'I', 'G', 'A', 'I', 'Y', 'P', 'G', 'N', 'G', 'D', 'T', 'S', 'Y', 'N', 'Q', 'K', 'F', 'K', 'G', 'K', 'A', 'T', 'L', 'T', 'A', 'D', 'K', 'S', 'S', 'S', 'T', 'A', 'Y', 'M', 'Q', 'L', 'S', 'S', 'L', 'T', 'S', 'E', 'D', 'S', 'A', 'V', 'Y', 'Y', 'C', 'A', 'S', 'L', 'G', 'S', 'S', 'Y', 'F', 'D', 'Y', 'W', 'G', 'Q', 'G', 'T', 'T', 'L', 'T', 'V', 'S', 'S']
Paratope predictions [4.83349077e-02 1.09023945e-02 3.84533731e-03 4.25319422e-06
 9.41727740e-06 1.17776506e-06 6.09542440e-06 2.35673213e-07
 1.64598305e-07 7.30653892e-06 1.16667547e-06 2.06242476e-06
 2.40918544e-05 7.64040465e-07 1.13476165e-06 5.32894956e-06
 2.44953458e-06 6.70739291e-06 2.37974255e-05 8.13638223e-08
 2.60763727e-07 5.90435185e-08 5.09770354e-04 3.60147911e-04
 1.91266846e-03 9.11799148e-02 1.22109085e-01 1.58884570e-01
 3.60358786e-03 1.19144030e-01 5.95673621e-01 6.43028498e-01
 9.29080367e-01 7.46257894e-04 8.19819331e-01 2.63847269e-05
 2.45079445e-03 6.36126060e-06 1.12615944e-05 2.64983584e-07
 1.37935376e-05 3.29489703e-05 5.73143079e-05 2.32888669e-05
 1.02728454e-05 4.14992654e-04 7.02820718e-02 3.25348228e-05
 4.90625207e-05 7.38208175e-01 7.66362399e-02 9.83155131e-01
 2.51317993e-02 1.05328552e-01 7.74510145e-01 2.35613957e-02
 8.83551657e-01 6.62648201e-01 8.68965328e-01 4.09811996e-02
 8.73022620e-03 4.30480763e-02 2.06377730e-03 1.11268331e-04
 5.25828563e-02 1.05413247e-03 1.26212499e-05 1.53439942e-05
 4.46972932e-04 2.91066011e-04 2.09803067e-04 5.58696338e-04
 6.98057702e-05 1.35148140e-02 4.19508433e-03 1.12148191e-04
 2.47820443e-03 2.91522497e-06 7.37539438e-07 3.22784108e-05
 1.46306050e-07 8.45733030e-06 7.02811391e-08 2.62050562e-05
 2.69241737e-05 1.74776901e-07 1.87373814e-07 1.86153216e-07
 9.19633749e-05 5.47690206e-06 7.16058878e-07 8.75153603e-08
 1.90661831e-06 2.76742583e-07 4.02055502e-06 8.10264919e-06
 1.07160481e-02 1.28381774e-01 9.58152533e-01 9.38068092e-01
 9.39873934e-01 8.96842182e-01 3.43691796e-01 4.63340618e-02
 2.63678223e-01 6.38445020e-02 2.92607513e-03 6.61719287e-06
 1.53246889e-04 2.97963379e-06 1.58954023e-07 5.17281435e-08
 2.30384867e-08 5.10915825e-08 8.91135343e-08 4.00957759e-07
 7.72467683e-06]

### single chain

In [5]:
test_heavy=pd.read_csv("./heavy.csv")
paratope_test_heavy=predict_paratope(test_heavy, single_chain=True)
paratope_test_heavy.head(5)

2025-12-25T21:05:05.873412Z [info     ] Loading training summary dictionary. path=/home/athenes/Paraplume/paraplume/trained_models/large/summary_dict.json
2025-12-25T21:05:05.911012Z [info     ] Loading model.                 path=/home/athenes/Paraplume/paraplume/trained_models/large/checkpoint.pt

  0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:00<00:00,  1.66it/s]
100%|██████████| 1/1 [00:02<00:00,  2.42s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 184.56it/s]
100%|██████████| 1/1 [00:03<00:00,  3.05s/it]
100%|██████████| 1/1 [00:05<00:00,  5.06s/it]
100%|██████████| 1/1 [00:00<00:00,  2.60it/s]
100%|██████████| 1/1 [00:03<00:00,  3.14s/it]

,sequence_heavy,sequence_light,model_prediction_heavy,model_prediction_light
0,QAYLQQSGAELVKPGASVKMSCKASDYTFTNYNMHWIKQTPGQGLE...,,"[0.06365915, 0.01992693, 0.005147011, 2.176086...",[]
1,EFQLQQSGPELVKPGASVRMSCKASGYTFASYVMHWVRQNPGQGLE...,,"[0.11589474, 0.045017295, 0.0011071792, 2.1546...",[]
2,EFQLQQSGPELVKPGTSVKMSCKASGYTFSDYVLHWVKPKPGQGLE...,,"[0.13037546, 0.047974225, 0.0010795749, 1.1507...",[]
3,EFQLQQSGPELVKPGASVKMSCKASGYTFSNYVLHWVKQRPGQGLE...,,"[0.10423852, 0.052239805, 0.00092409056, 2.280...",[]
4,EFQLQQSGPELVKPGASVKMSCKASGYTFTSYVIHWVKQKPGQGLE...,,"[0.11994196, 0.06928268, 0.0010056219, 5.92382...",[]

### With Paraplume-s

In [6]:
test_heavy=pd.read_csv("./heavy.csv")
paratope_test_heavy=predict_paratope(test_heavy, single_chain=True, large=False)
paratope_test_heavy.head(5)

2025-12-25T21:05:20.783154Z [info     ] Loading training summary dictionary. path=/home/athenes/Paraplume/paraplume/trained_models/small/summary_dict.json
2025-12-25T21:05:20.797588Z [info     ] Loading model.                 path=/home/athenes/Paraplume/paraplume/trained_models/small/checkpoint.pt

  0%|          | 0/1 [00:00<?, ?it/s]

100%|██████████| 1/1 [00:04<00:00,  4.98s/it]

,sequence_heavy,sequence_light,model_prediction_heavy,model_prediction_light
0,QAYLQQSGAELVKPGASVKMSCKASDYTFTNYNMHWIKQTPGQGLE...,,"[0.048844993, 0.009345077, 0.013855274, 0.0019...",[]
1,EFQLQQSGPELVKPGASVRMSCKASGYTFASYVMHWVRQNPGQGLE...,,"[0.04437572, 0.012087607, 0.0011726064, 0.0003...",[]
2,EFQLQQSGPELVKPGTSVKMSCKASGYTFSDYVLHWVKPKPGQGLE...,,"[0.057581093, 0.01399147, 0.0009839429, 0.0002...",[]
3,EFQLQQSGPELVKPGASVKMSCKASGYTFSNYVLHWVKQRPGQGLE...,,"[0.05387679, 0.0129488725, 0.0009610752, 0.000...",[]
4,EFQLQQSGPELVKPGASVKMSCKASGYTFTSYVIHWVKQKPGQGLE...,,"[0.060365915, 0.017050423, 0.0016370759, 0.000...",[]

# Inference for a sequence

In [7]:
heavy_seq=test["sequence_heavy"].values[0]
light_seq=test["sequence_light"].values[0]

In [8]:
# Paired chain
paratope_heavy, paratope_light=predict_paratope_seq(sequence_heavy=heavy_seq,sequence_light=light_seq)

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 128.14it/s]

In [9]:
print(paratope_heavy)

[0.0483349934220314, 0.010902296751737595, 0.003845377592369914, 4.253166025591781e-06, 9.4172673925641e-06, 1.1777583495131694e-06, 6.09547714702785e-06, 2.3567436358007399e-07, 1.645967415697669e-07, 7.306468887691153e-06, 1.166679908237711e-06, 2.062420890069916e-06, 2.4091577870422043e-05, 7.640426247235155e-07, 1.1347605095579638e-06, 5.328964107320644e-06, 2.449534576953738e-06, 6.707419288431993e-06, 2.3797425455995835e-05, 8.136304074923828e-08, 2.6076497761096107e-07, 5.9042960742772266e-08, 0.0005097715184092522, 0.0003601495991460979, 0.0019126794068142772, 0.09117971360683441, 0.1221085637807846, 0.15888461470603943, 0.003603582503274083, 0.11914396286010742, 0.5956739187240601, 0.6430292129516602, 0.9290804862976074, 0.0007462615030817688, 0.8198186159133911, 2.638442128954921e-05, 0.0024508037604391575, 6.361302894219989e-06, 1.1261700819886755e-05, 2.6498511829231575e-07, 1.3793445759802125e-05, 3.294878115411848e-05, 5.7313871366204694e-05, 2.3288775992114097e-05, 1.0272864528815262e-05, 0.00041499320650473237, 0.07028219103813171, 3.25350665661972e-05, 4.906252070213668e-05, 0.7382086515426636, 0.07663655281066895, 0.9831551313400269, 0.025131706148386, 0.10532819479703903, 0.7745104432106018, 0.023561395704746246, 0.8835513591766357, 0.6626492142677307, 0.8689661026000977, 0.04098138585686684, 0.008730296045541763, 0.04304811358451843, 0.0020637831185013056, 0.00011126928438898176, 0.05258297175168991, 0.0010541295632719994, 1.2621201676665805e-05, 1.534391958557535e-05, 0.0004469703999347985, 0.0002910640905611217, 0.00020980284898541868, 0.0005586998304352164, 6.980577018111944e-05, 0.013514820486307144, 0.0041950843296945095, 0.00011214797996217385, 0.002478220732882619, 2.9152083698136266e-06, 7.375513746410434e-07, 3.2278254366246983e-05, 1.4630715838848118e-07, 8.457305739284493e-06, 7.028221205018781e-08, 2.6205107133137062e-05, 2.6924049961962737e-05, 1.747765594473094e-07, 1.8737256368694943e-07, 1.8615375552144542e-07, 9.196371684083715e-05, 5.476881597132888e-06, 7.160499535530107e-07, 8.751552371677462e-08, 1.9066310414928012e-06, 2.767452258467529e-07, 4.020593678433215e-06, 8.10263281891821e-06, 0.010716082528233528, 0.12838269770145416, 0.9581525325775146, 0.9380680918693542, 0.9398739337921143, 0.8968421816825867, 0.3436920642852783, 0.04633425176143646, 0.2636789381504059, 0.06384465843439102, 0.0029260695446282625, 6.61722378936247e-06, 0.00015324747073464096, 2.97963651973987e-06, 1.5895402327714692e-07, 5.172814354637012e-08, 2.3038884577886165e-08, 5.109158252025736e-08, 8.911369775432831e-08, 4.009543488336931e-07, 7.724602255620994e-06]

In [10]:
# Heavy chain only
paratope_heavy, _ =predict_paratope_seq(sequence_heavy=heavy_seq, single_chain=True)

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 187.90it/s]

In [11]:
# light chain only
_, paratope_light=predict_paratope_seq(sequence_light=light_seq, single_chain=True)

Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00, 186.93it/s]